eRoutingSlip/Models/LinkedListSignatureNode.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace eRoutingSlip.Models
{
    public class LinkedListSignatureNode
    {
        public virtual int ID { get; set; }
        public virtual Signature Data { get; set; }

        public virtual LinkedListSignatureNode PrevSNode { get; set; }
        public virtual LinkedListSignatureNode NextSNode { get; set; }

        public virtual int RoutingSlipID { get; set; }

        [InverseProperty("PrevSNode")]
        public virtual ICollection<LinkedListSignatureNode> PrevSNodes { get; set; }
        [InverseProperty("NextSNode")]
        public virtual ICollection<LinkedListSignatureNode> NextSNodes { get; set; }
    }



}

eRoutingSlip/Controllers/DetailsController.cs
using eRoutingSlip.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eRoutingSlip.Controllers
{
    public class DetailsController : Controller
    {
        ERoutingSlipDB _db = new ERoutingSlipDB();

        public ActionResult OpenDocument(int id)
        {
            var model = _db.RoutingSlips.Find(id);
            var link = model.DocumentName;
            return Redirect(link);
        }

        public ActionResult Forward(int id)
        {
            // Change current name attribute of routing slip
            //LinkedListSignatureNode llsn = _db.LinkedListSignatureNodes.SingleOrDefault(linkedlist => linkedlist.RoutingSlipID == id && linkedlist.Data.SignatureName == currname);
            LinkedListSignature lls = _db.LinkedListSignatures.SingleOrDefault(link => link.RoutingSlipID == id);
            LinkedListSignatureNode llsn = _db.LinkedListSignatureNodes.SingleOrDefault(node => node.Data.SignatureName == lls.CurrentName && node.RoutingSlipID == id);
            
            RoutingSlip rs = _db.RoutingSlips.Find(id);
            rs.LinkedListSignature.CurrentName = llsn.NextSNode.Data.SignatureName;
            //rs.LinkedListSignature.CurrentName = llsn.NextSNode.Data.SignatureName;
            //var newCurrent = llsn.NextSNode.Data.SignatureName;
            llsn.Data.DateRouted = DateTime.Now;
            //var model = _db.RoutingSlips.Find(id);
            //model.LinkedListSignature.CurrentName = newCurrent;

            if (ModelState.IsValid)
            {
                _db.SaveChanges();
                return RedirectToAction("Index", "RoutingSlip");
            }
            return View(id);
        }

        //// GET: Details
        //public ActionResult Index()
        //{
        //    return View();
        //}

        //// GET: Details/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        //// GET: Details/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Details/Create
        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Details/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: Details/Edit/5
        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Details/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: Details/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

eRoutingSlip/Controllers/LinkedListSignatureNodeController.cs
using eRoutingSlip.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eRoutingSlip.Controllers
{
    public class LinkedListSignatureNodeController : Controller
    {
        ERoutingSlipDB _db = new ERoutingSlipDB();

        // GET: LinkedListSignatureNode
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DeleteNode(int id)
        {
            var model = _db.LinkedListSignatureNodes.Find(id);

            var LLmodel = _db.LinkedListSignatureNodes;
            var LLmodelID = model.RoutingSlipID;

            foreach (LinkedListSignatureNode l in LLmodel)
            {
                if (l.RoutingSlipID == model.RoutingSlipID && l.ID == model.ID)
                {
                    if (model.NextSNode != null) // middle of the list
                    {
                        model.NextSNode.PrevSNode = model.PrevSNode;
                        model.PrevSNode.NextSNode = model.NextSNode;
                        LLmodel.Remove(model);
                    }
                    else
                    {
                        LLmodel.Remove(model);
                    }
                }
            }

            if (ModelState.IsValid)
            {
                _db.SaveChanges();

                return RedirectToAction("Details", new { id = LLmodelID });
            }
            else
            {
                return View(model);
            }

        }

        public ActionResult Details(int id)
        {
            var LLmodel = _db.LinkedListSignatureNodes;
            var query = from n in LLmodel
                        where n.RoutingSlipID == id
                        select n;
            if (ModelState.IsValid)
            {

                return View(query);
            }
            else
            {
                return View(LLmodel);
            }
        }

        // GET: LinkedListSignatureNode/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LinkedListSignatureNode/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LinkedListSignatureNode/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LinkedListSignatureNode/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LinkedListSignatureNode/Delete/5
        public ActionResult Delete(int id)
        {
            LinkedListSignatureNode llsn = _db.LinkedListSignatureNodes.Find(id);
            if (llsn == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("DeleteNode", new { id = llsn.ID });
        }


        public ActionResult CreateNode(int id)
        {
            var model = _db.LinkedListSignatureNodes.Find(id);
            LinkedListSignatureNode newNode = new LinkedListSignatureNode();
            newNode.RoutingSlipID = model.RoutingSlipID;
            if (model.NextSNode == null)
            {
                model.NextSNode = newNode;
            }
            else // middle node
            {
                model.NextSNode.PrevSNode = newNode;
                model.NextSNode = newNode;
                newNode.PrevSNode = model;
                newNode.NextSNode = model.NextSNode;
            }

            Signature newSignature = new Signature();
            newSignature.RoutingSlipID = model.RoutingSlipID;
            newSignature.Status = "N/A";
            newNode.Data = newSignature;
            _db.LinkedListSignatureNodes.Add(newNode);

            if (ModelState.IsValid)
            {

                //_db.SaveChanges();
                return RedirectToAction("CreateSignature", new { id = newNode.ID });
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult NewNode(int id, string n)
        {
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult CreateSignature(int id)
        {
            var model = _db.LinkedListSignatureNodes.Find(id);
            return View(model);
        }

        //[HttpGet]
        //public ActionResult CreateSignature([Bind(Prefix = "id")] int linkId)
        //{
        //    var model = _db.LinkedListSignatureNodes.Find(linkId);
        //    if (model != null)
        //    {
        //        return View(model);
        //    }
        //    return HttpNotFound();
        //}

        [HttpPost]
        public ActionResult CreateSignature(LinkedListSignatureNode l)
        {

            if (ModelState.IsValid)
            {
                var modelID = l.RoutingSlipID;
                return RedirectToAction("Details", new { id = modelID });
            }
            else
            {
                return HttpNotFound();
            }

        }
        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

eRoutingSlip/Views/LinkedListSignatureNode/AddName.cshtml
@model eRoutingSlip.Models.LinkedListSignatureNode

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LinkedListSignatureNode</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RoutingSlipID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoutingSlipID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoutingSlipID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

eRoutingSlip/Views/LinkedListSignatureNode/CreateSignature.cshtml
@model eRoutingSlip.Models.LinkedListSignatureNode


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Signature</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Data.SignatureName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Data.SignatureName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Data.SignatureName, "", new { @class = "text-danger" })
        </div>
    </div>

    <input type="submit" value="Create" />

</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

eRoutingSlip/Views/LinkedListSignatureNode/Details.cshtml
@model IEnumerable<eRoutingSlip.Models.LinkedListSignatureNode>

@{
    ViewBag.Title = "SetPrevNext";
}



<table class="table" style="table-layout:fixed;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RoutingSlipID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            Previous
        </th>
        <th>
            Next
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RoutingSlipID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrevSNode.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NextSNode.ID)
            </td>
            <td>
                @if (item.PrevSNode == null)
                {
                    @Html.ActionLink("Add Name ", "#", "", null, new { onclick = "return ShowInput('label" + item.ID + "');" })
                }
                else
                {
                    //@Html.ActionLink("Add Name | ", "CreateNode", "LinkedListSignatureNode", new { id = item.ID }, null)
                    @Html.ActionLink("Add Name |", "#", "", null, new { onclick = "return ShowInput('label" + item.ID + "');" })
                    @Html.ActionLink("  Remove ", "DeleteNode", "LinkedListSignatureNode", new { id = item.ID }, null)
                }
            </td>
        </tr>
        <tr id="@("label"+item.ID)" class="inputholder" style="background-color:silver; color:black;">
            <td></td>
            <td>
                <i>New entry</i>
            </td>
            <td>
                @Html.ValidationMessage("*")
                <input type="text" id="@("input"+item.ID)" value="" />
            </td>
            <td></td>
            <td>
                @*@Html.ActionLink(" Save | ", "CreateNode", "LinkedListSignatureNode", new { onclick = "return Validate('input" + item.ID + "');" })*@
                @*@Html.ActionLink(" Save | ", "CreateNode", new { id = item.ID }, new { onclick = "return Validate(item.ID)" })*@
                @*@Html.ActionLink(" Save | ", "CreateNode", "LinkedListSignatureNode", new { onclick = "return Validate('input" + item.ID + "');" })*@
                @Html.ActionLink(" Save | ", "#", "#", new { onclick = "return Validate(" + item.ID + ");" })
                @Html.ActionLink(" Cancel", "#", "", null, new { onclick = "return HideInput('label" + item.ID + "');" })
            </td>
        </tr>
    }



</table>

<script>

    function ShowInput(id) {
        document.getElementById(id).style.display = "table-row";
        return false;
    }
    function HideInput(id) {
        document.getElementById(id).style.display = "none";
        return false;
    }

    //function Validate(id) {
    //    var a = document.getElementById(id);
    //    if (a.value.length >= 1) {
    //        var name = a.value;
    //        return a;
    //    }
    //    else {
    //        return false;

    //    }
    //}
    function getName(id) {
        var n = document.getElementById(id).value;
        return n;
    }

    function Validate(id) {
        var newId = "input" + id;
        alert(newId);

        name = getName(newId);
        alert(name);

        //var params = "{'id': '" + $("#id").val() + "'}";


         //gives error alert
        //$.ajax({
        //    url: '<%: Url.Action("NewNode", "LinkedListSignatureNode")',
        //    data: {
        //        'id': id,
        //        'n': name
        //    },
        //    type: 'GET',
        //    cache: false,
        //    contentType: 'application/json; charset=utf-8',
        //    dataType: 'html',
        //    success: function (result) {
        //        alert('success');
        //    },
        //    error: function (response) {
        //        alert('error');
        //    }

        //});

        //window.location.href = '"/LinkedListSignatureNode/NewNode/id=" + id + "/n=" + name',true;
        window.location.replace("/LinkedListSignatureNode/NewNode/id=" + id + "?n=" + name+"/") //redirects
        //window.location.replace("/LinkedListSignatureNode/NewNode/" + id + "/" + name+"/")

        //document.location.href = '"/LinkedListSignatureNode/NewNode/id=" + id + "/n=" + name', true;
        return false;

        // not working
        //$.ajax({
        //    url: 'NewNode',
        //    data: { id: id, n: name }
        //}).done(function () {
        //    alert('Added');
        //});
    }


</script>

<style>
    .inputholder {
        display: none;
    }
</style>

eRoutingSlip/Views/LinkedListSignatureNode/UpdateList.cshtml
@model IEnumerable<eRoutingSlip.Models.LinkedListSignatureNode>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RoutingSlipID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrevSNode.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NextSNode.ID)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RoutingSlipID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrevSNode.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NextSNode.ID)
            </td>
            <td>
                @Html.ActionLink("Add Name", "AddName", "LinkedListSignatureNode", new { id = item.ID }, null) |
                @Html.ActionLink("Remove", "Delete", "LinkedListSignatureNode", new { id = item.ID }, null)
            </td>
        </tr>
    }

</table>